# Generated by Django 5.1.15 on 2026-05-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkingInsuranceCompany",
            new_name="WorkingInsuranceCompanies",
        ),
    ]
