# Generated by Django 5.1.15 on 2026-06-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_workinginsurancecompany_workinginsurancecompanies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkingCategory",
            new_name="ThpWorkingCategory",
        ),
    ]
