# Generated by Django 5.1.15 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_workingcategory_thpworkingcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthUserBackOffice",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
    ]
