# Generated by Django 5.1.15 on 2026-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_authuserbackoffice"),
    ]

    operations = [
        migrations.AddField(
            model_name="thpworkingcategory",
            name="last_name",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
