# Generated by Django 5.1.15 on 2026-06-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_thpworkingcategory_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workinginsurancecompanies",
            name="last_name",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="thpworkingcategory",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="workinginsurancecompanies",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
