# Generated by Django 5.1.15 on 2026-06-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_workinginsurancecompanies_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thpworkingcategory",
            name="last_name",
        ),
    ]
