# Generated by Django 5.1.15 on 2026-06-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_thpworkingcategory_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilethpissuingagent",
            name="orders_in_issuing",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
