# Generated by Django 5.1.15 on 2026-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profilethpissuingagent_orders_in_isssuing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilethpissuingagent",
            name="orders_in_issuing",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
