# Generated by Django 5.2.5 on 2026-07-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_profilethpissuingagent_orders_in_issuing"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("tag", models.CharField(blank=True, null=True)),
                ("token", models.CharField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
