# Generated by Django 5.2.5 on 2026-07-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_logintoken"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoginToken",
            new_name="ForeignLoginToken",
        ),
    ]
