# Generated by Django 5.2.5 on 2026-07-18 07:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_rename_logintoken_foreignlogintoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilethpissuingagent",
            name="working_days",
        ),
        migrations.DeleteModel(
            name="WorkingDay",
        ),
        migrations.AddField(
            model_name="profilethpissuingagent",
            name="working_days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "saturday"),
                        (1, "sunday"),
                        (2, "monday"),
                        (3, "tuesday"),
                        (4, "wednesday"),
                        (5, "thursday"),
                        (6, "friday"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
