# Generated by Django 5.2.5 on 2026-07-21 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_profilethpissuingagent_working_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilethpissuingagent",
            name="working_days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "شنبه"),
                        (1, "یکشنبه"),
                        (2, "دوشنبه"),
                        (3, "سه\u200cشنبه"),
                        (4, "چهارشنبه"),
                        (5, "پنج\u200cشنبه"),
                        (6, "جمعه"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
