# Generated by Django 5.2.5 on 2026-07-26 09:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_profilethpissuingagent_working_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="BnplAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BnplWorkingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfileBnplIssuingAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "working_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (0, "شنبه"),
                                (1, "یکشنبه"),
                                (2, "دوشنبه"),
                                (3, "سه\u200cشنبه"),
                                (4, "چهارشنبه"),
                                (5, "پنج\u200cشنبه"),
                                (6, "جمعه"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_working", models.BooleanField(default=True)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile",
                        to="accounts.bnplaccounts",
                    ),
                ),
                (
                    "profile_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "working_category",
                    models.ManyToManyField(
                        blank=True, to="accounts.bnplworkingcategory"
                    ),
                ),
            ],
        ),
    ]
