# Generated by Django 5.2.5 on 2026-07-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_bnplaccounts_bnplworkingcategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileBnplIssuingAgent",
            new_name="ProfileBnplAgent",
        ),
    ]
