# Generated by Django 5.2.5 on 2026-07-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_rename_profilebnplissuingagent_profilebnplagent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilebnplagent",
            name="account",
        ),
        migrations.RemoveField(
            model_name="profilebnplagent",
            name="working_category",
        ),
        migrations.RemoveField(
            model_name="profilebnplagent",
            name="profile_user",
        ),
        migrations.DeleteModel(
            name="BnplAccounts",
        ),
        migrations.DeleteModel(
            name="BnplWorkingCategory",
        ),
        migrations.DeleteModel(
            name="ProfileBnplAgent",
        ),
    ]
