# Generated by Django 5.2.5 on 2026-07-27 09:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BnplAccountList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parslogic_account", models.CharField(unique=True)),
                ("agent_name", models.CharField(blank=True, null=True, unique=True)),
                (
                    "working_day",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (0, "شنبه"),
                                (1, "یکشنبه"),
                                (2, "دوشنبه"),
                                (3, "سه\u200cشنبه"),
                                (4, "چهارشنبه"),
                                (5, "پنج\u200cشنبه"),
                                (6, "جمعه"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_working", models.BooleanField(default=True)),
            ],
        ),
    ]
