# Generated by Django 5.2.5 on 2026-07-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BnplAccountList",
            new_name="BnplAccount",
        ),
    ]
